### ISSUE TITLE
Slick 3 Support

### ISSUE THREAD

**Issue by raulraja** [strongtyped/active-slick#16]
Hi, Is this project still actively maintained? If so is there a roadmap to support the upcoming Slick 3 release? thanks!

**Comment by rcavalcanti** [comment]
Hi Raul, 
The project is not dead. 
I was working on the port to Slick3, but left it aside for a while. I'll probably restart work next week. 

I can eventually push a branch this week. If you want to help we can work together on a branch.

**Comment by rcavalcanti** [comment]
Hi Raul, 

Here is a branch containing a port to Slick 3.0
https://github.com/strongtyped/active-slick/tree/feature/slick-3.0

It's work in progress. Still need some clean-up and re-enabling / fixing some tests.

Feedback is welcome!

**Comment by raulraja** [comment]
Thanks @rcavalcanti. We are planning a migration to Slick 3 soon. I will check it out then and will let you know if I find any issues.

**Comment by diwalak** [comment]
Would be good to have a release now that Slick 3.0 is out

**Comment by rcavalcanti** [comment]
@diwalak the slick-3.0 is almost ready. You can eventually start using it for the moment.

**Comment by rodricifuentes1** [comment]
I cannot wait for the slick-3.0 port. :)
When is it going to be available?
Thank you very much for all your work!

**Comment by rcavalcanti** [comment]
Hi Rodrigo,

Unfortunately this won't help soon. I'm on vacation right now. I'm only
back in August.

There is a branch for Slick-3.0 (feature/slick-3.0). You can have a look on
it for the moment.

However, this branch is undergoing a new refactoring. After porting
active-slick to Slick 3.0, I started to play around with some new ideas and
realised that I could reduce its complexity a little bit.

I'm still working on it and will run a major refactoring / clean-up after
my vacations. In Slick 3.0 everything is about DBIO, so I think that
active-slick should take the same path.

That said, you can have a look at the branch I mentioned above, but the
final release will be different.

I hope you can wait a little bit.

Have a nice day!

Cheers,

Renato

**Comment by diwalak** [comment]
Any progress on this ?

Great work so far !!

**Comment by rcavalcanti** [comment]
Yes, have a look on latest commit on this branch:
https://github.com/strongtyped/active-slick/tree/feature/slick-3.0

This is pretty much what will be released. I hope.

I'm writing some documentation.

**Comment by rcavalcanti** [comment]
Hi Guys, 

The is a new version now support Slick 3.0. It should show up on Maven Central in a couple of minutes. 

This version has a quite different approach. Since I had to do a lot of refactoring because of Slick 3.0, I decide to turn it inside out. No Cake Pattern is need, not special Tables to implements. Just plain old Slick mapping with some extra stuff to glue everything together. 

See README file for more info or join me at Gitter.
https://gitter.im/strongtyped/active-slick

Enjoy!
