### ISSUE TITLE
Slick code generator

### ISSUE THREAD

**Issue by odwrotnie** [strongtyped/active-slick#17]
How do you use Slick code generator with Active Slick?

**Comment by rcavalcanti** [comment]
Hi Pawel, 
 
I don't and to be honest I never tried it.
It can be a good experiment to generate Active Slick code from DB schema using Slick code generator. Could be a separated model. 

I'll not be playing with that in the coming months, but if you want to fork and work on that, be my guest. :-)

**Comment by rcavalcanti** [comment]
BTW, I'll close this ticket. We can continue discussing it, if you want, on the Gitter chat room
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/strongtyped/active-slick?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by mkotsbak** [comment]
I'm wondering about this as well. Try to use customization of the code generation to extend the correct traits in this project.

**Comment by rcavalcanti** [comment]
@mkotsbak are you working on this? 
If so, please take on consideration feature/slick-3.0 branch. 
Don't hesitate to send a pull request. It'll be great to have it in a separate module.

**Comment by rcavalcanti** [comment]
Btw, if you are working on that or plan to work, we can reopen this ticket. 

I closed it because I had no plans to implement it for the moment and didn't want to give people the impression it'll happen.

**Comment by mkotsbak** [comment]
I might give it a try if I get some time. Actually I think it might be possible to just get it working by customizing the code generator in Slick, so the result might not be a code module, but a Wiki page used as a template.
