### ISSUE TITLE
Support for type-safe Ids

### ISSUE THREAD

**Issue by rcavalcanti** [strongtyped/active-slick#20]
As a user of ActiveSlick I want to define my own Ids as a custom type, as in:
```scala
case class ProductId(value:Long)
case class Product(name:String, price:Double, id:Option[ProductId] = None)
```

**Comment by ugoenyioha** [comment]
Hi @rcavalcanti Any timeline for when this will be implemented?

**Comment by rcavalcanti** [comment]
I don't have a timeline. These are some improvements ideas I have, but nothing planned for the moment. 

To be honest, I'll be quite busy in the coming months so I'm may only have a look on it towards mid-November.

But I'm accepting contributions! :-)

**Comment by mkotsbak** [comment]
That would be nice yes. Are there any workaround for now? Maybe manual mapping of the ID column?

**Comment by rcavalcanti** [comment]
Actually Slick support it already. 
Have a look at: http://slick.typesafe.com/doc/2.0.0/userdefined.html#scalar-types

This issue is actually obsolete

**Comment by mkotsbak** [comment]
That was something I was suspecting, but I thought ActiveSlick needed support as well :)
