### ISSUE TITLE
Bring dynamic columns update to active-slick.

### ISSUE THREAD

**Issue by djx314** [strongtyped/active-slick#25]
Are you interested in merge the project write by me and jilen to active slick?
<https://github.com/scalax/slick-summer>
It's a stronger's slick update. It can update the columns decided in runtime without relfect and macro. Just see the use in the test case.
<https://github.com/scalax/slick-summer/blob/master/src/test/scala/org/xarcher/summer/test/DynamicUpdateTest.scala>

**Comment by rcavalcanti** [comment]
Hi @djx314,

That sounds great. Merging it inside active-slick could be an option, but don't you think you could have it merged into Slick itself?

If you prefer to bring it to active-slick, please fork and send a PR. 
I'll need more documentation (in English) and some time to analyse it and assess the impact. But yes, I'm definitely interested.

**Comment by djx314** [comment]
Just wait for 2 - 3 day, now has a bug, I have a solution, just some macro, HaHa!
Then I can provide the full documention, I think I can't provide a pull request. Because I just found the greate repo and read the documention today.
I can tell you how the code works, and
```
You can change the namespace of my code, don't care.
```
Now let me fix the bug, It's 3:52 am in China, zzz

**Comment by djx314** [comment]
Bug fix, hope for @jilen to provide a full document because of my bad English.
And if you want to test it, be careful to test H2Driver and MysqlDriver both and confirm that
```sql
Mysql
select `name` from ...
```
```sql
H2
select "name" from ...
```
It a simple way to sure that you not to provide a JDBCDriver anywhere.

**Comment by djx314** [comment]
I am wrirting a extension for slick <https://github.com/scalax/slick-archer>, hope for fixing <https://github.com/strongtyped/active-slick/issues/26> and I want to use it to the dynamic update extension. Perhaps it will watse a few weeks.

**Comment by rcavalcanti** [comment]
May I close this ticket? Have you done some more work on it or this is a dead path?

**Comment by djx314** [comment]
Oh, sorry for forgetting it. Now I deal to work with my own project and not planning to merge it with active-slick because the api is not stable. Welcome to see https://github.com/scalax/hf
